

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_departments (
    department_id TEXT PRIMARY KEY,
    name_department TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_users (
    login TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    job_title TEXT,
    department_id TEXT REFERENCES sbx_dfip_ocpp.notes_departments(department_id)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_email_recipients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    fio TEXT NOT NULL,
    job_title TEXT,
    salutation TEXT,
    gender TEXT NOT NULL CHECK (gender IN ('муж', 'жен')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login),
    CONSTRAINT uq_notes_email_recipients_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_notebooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login),
    closed INTEGER NOT NULL DEFAULT 0,
    department_id TEXT REFERENCES sbx_dfip_ocpp.notes_departments(department_id)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notebook_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_notebooks(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_sections(id),
    title TEXT NOT NULL,
    tag TEXT,
    body_html TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_notebook_owners (
    notebook_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_notebooks(id),
    user_login TEXT NOT NULL REFERENCES sbx_dfip_ocpp.notes_users(login),
    PRIMARY KEY (notebook_id, user_login)
);

-- Helpful indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_notes_sections_notebook_id ON sbx_dfip_ocpp.notes_sections (notebook_id);
CREATE INDEX IF NOT EXISTS idx_notes_pages_section_id ON sbx_dfip_ocpp.notes_pages (section_id);
CREATE INDEX IF NOT EXISTS idx_notes_pages_tag ON sbx_dfip_ocpp.notes_pages (tag);
CREATE INDEX IF NOT EXISTS idx_notes_notebook_owners_user_login ON sbx_dfip_ocpp.notes_notebook_owners (user_login);
CREATE INDEX IF NOT EXISTS idx_notes_notebooks_closed ON sbx_dfip_ocpp.notes_notebooks (closed);
CREATE INDEX IF NOT EXISTS idx_notes_email_recipients_email ON sbx_dfip_ocpp.notes_email_recipients (email);
CREATE INDEX IF NOT EXISTS idx_notes_email_recipients_fio ON sbx_dfip_ocpp.notes_email_recipients (fio);

-- Прикрепленные к страницам файлы и ссылки
CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_page_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_pages(id) ON DELETE CASCADE,
    attachment_type TEXT NOT NULL DEFAULT 'file' CHECK (attachment_type IN ('file', 'link')),
    file_name TEXT NOT NULL,
    mime_type TEXT,
    file_size BIGINT,
    file_data BYTEA,
    url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login),
    question_number TEXT,
    CHECK (
        (attachment_type = 'file' AND file_data IS NOT NULL)
        OR (attachment_type = 'link' AND url IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_notes_page_attachments_page_id ON sbx_dfip_ocpp.notes_page_attachments (page_id);
CREATE INDEX IF NOT EXISTS idx_notes_page_attachments_created_at ON sbx_dfip_ocpp.notes_page_attachments (created_at DESC);

-- История изменений страниц (логирование INSERT/UPDATE/DELETE)
CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_pages_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id INTEGER NOT NULL,
    operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by TEXT NOT NULL DEFAULT CURRENT_USER,
    old_row JSONB,
    new_row JSONB
);

CREATE INDEX IF NOT EXISTS idx_notes_pages_history_page_id_changed_at
    ON sbx_dfip_ocpp.notes_pages_history (page_id, changed_at DESC);

CREATE OR REPLACE FUNCTION sbx_dfip_ocpp.trg_notes_pages_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO sbx_dfip_ocpp.notes_pages_history (page_id, operation, changed_by, new_row)
        VALUES (NEW.id, 'INSERT', CURRENT_USER, to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO sbx_dfip_ocpp.notes_pages_history (page_id, operation, changed_by, old_row, new_row)
        VALUES (NEW.id, 'UPDATE', CURRENT_USER, to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO sbx_dfip_ocpp.notes_pages_history (page_id, operation, changed_by, old_row)
        VALUES (OLD.id, 'DELETE', CURRENT_USER, to_jsonb(OLD));
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_notes_pages_history ON sbx_dfip_ocpp.notes_pages;
CREATE TRIGGER trg_notes_pages_history
AFTER INSERT OR UPDATE OR DELETE ON sbx_dfip_ocpp.notes_pages
FOR EACH ROW
EXECUTE FUNCTION sbx_dfip_ocpp.trg_notes_pages_history();
