-- PostgreSQL schema for the OneNote-like app (matches onenote.duckdb structure)

CREATE SCHEMA IF NOT EXISTS sbx_dfip_ocpp;

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_department TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_users (
    login TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    can_create_notebook BOOLEAN NOT NULL DEFAULT FALSE,
    department_id INTEGER REFERENCES sbx_dfip_ocpp.notes_departments(department_id)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_notebooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login),
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    department_id INTEGER REFERENCES sbx_dfip_ocpp.notes_departments(department_id)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notebook_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_notebooks(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login)
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_sections(id),
    title TEXT NOT NULL,
    tag TEXT,
    body_html TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT REFERENCES sbx_dfip_ocpp.notes_users(login),
    tag TEXT
);

CREATE TABLE IF NOT EXISTS sbx_dfip_ocpp.notes_notebook_owners (
    notebook_id INTEGER NOT NULL REFERENCES sbx_dfip_ocpp.notes_notebooks(id),
    user_login TEXT NOT NULL REFERENCES sbx_dfip_ocpp.notes_users(login),
    PRIMARY KEY (notebook_id, user_login)
);

-- Helpful indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_notes_sections_notebook_id ON sbx_dfip_ocpp.notes_sections (notebook_id);
CREATE INDEX IF NOT EXISTS idx_notes_pages_section_id ON sbx_dfip_ocpp.notes_pages (section_id);
CREATE INDEX IF NOT EXISTS idx_notes_pages_tag ON sbx_dfip_ocpp.notes_pages (tag);
CREATE INDEX IF NOT EXISTS idx_notes_notebook_owners_user_login ON sbx_dfip_ocpp.notes_notebook_owners (user_login);
CREATE INDEX IF NOT EXISTS idx_notes_notebooks_closed ON sbx_dfip_ocpp.notes_notebooks (closed);


-- Optional seed for default user used by the app logic; safe to run multiple times.
INSERT INTO sbx_dfip_ocpp.notes_users (login, full_name)
VALUES ('user1', 'user1')
	,('user2', 'user2')
	,('user3', 'user3')
ON CONFLICT (login) DO NOTHING;
